//THIS FILE IS GENERATED BY "add_images.py"
"use strict";

const IMAGE_DATA = {
    "all_images": [
        "2025_10_28__13_57_15__56.jpg"
    ],
    "by_filename": {
        "2025_10_28__13_57_15__56.jpg": {
            "ISO": 1600,
            "aperture": 2.2,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:28 13:57:15",
            "file_size": "327 kB",
            "focal": "135.0 mm",
            "image_height": 3579,
            "image_width": 5362,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/2500",
            "tags": [
                "Allvi"
            ]
        }
    },
    "by_rating": {
        "3": [
            "2025_10_28__13_57_15__56.jpg"
        ]
    },
    "by_tag": {
        "Allvi": [
            "2025_10_28__13_57_15__56.jpg"
        ]
    },
    "directory": "img"
}
Object.freeze(IMAGE_DATA);
