//THIS FILE IS GENERATED BY "add_images.py"
"use strict";

const IMAGE_DATA = {
    "about": {
        "name": "<h2>Emil Bratt</h2>",
        "bio": "<p>Velkommen!</p><p>Jeg er en eksfotograf som startet for fullt i 2011 og sluttet under Covid.\nHar vært med på mange spennende oppdrag gjennom min karriere.</p><p>Jeg fotograferer alt mulig. Da jeg drev proffesjonelt,\nfotograferte jeg sport, konsert, event, bryllup, gravid, nyfødt og sist men ikke minst, natur.</p><p>Har veldig lyst å starte opp proffesjonelt igjen,\nmen først skal det taes bilder rekreasjonelt. :)\nBildene du finner her er tilgjengelige for nedlasting og helt gratis for deg som privatperson.\nDet vil komme flere bilder etter hvert.</p><p>Tidligere delte jeg alt sammen på facebook og instagram, men det gjør jeg ikke lenger.\nSosiale medier har desverre blitt vanskeligere å bruke for personer uten brukerkonto,\nså jeg tok hammern fatt og snekra sammen denne nettsida.\nEr du kanskje en utvikler selv og lurer på hva som holder denne nettsida sammen? Her ligger\n<button><a href=\"https://github.com/emilbratt/frifoto.emilbratt.no/\">kildekode!</a></button>\n</p>"
    },
    "all_images": [
        "2024_05_20__19_51_15__09.jpg",
        "2024_05_30__21_31_13__10.jpg",
        "2024_05_30__21_37_10__46.jpg",
        "2024_05_30__21_39_00__33.jpg",
        "2024_10_14__13_28_15__68.jpg",
        "2025_05_26__17_44_37__86.jpg",
        "2025_05_26__17_44_51__25.jpg",
        "2025_05_26__17_45_25__57.jpg",
        "2025_10_23__14_31_27__44.jpg",
        "2025_10_23__14_39_57__13.jpg",
        "2025_10_23__14_46_23__77.jpg",
        "2025_10_23__14_55_24__12.jpg",
        "2025_10_23__14_58_44__79.jpg",
        "2025_10_23__15_07_05__43.jpg",
        "2025_10_23__15_17_47__46.jpg",
        "2025_10_23__15_26_43__11.jpg",
        "2025_10_28__13_57_15__56.jpg",
        "2025_10_28__14_07_09__1.jpg",
        "2025_10_28__14_19_24__99.jpg",
        "2025_10_28__14_22_47__12.jpg",
        "2025_10_28__14_23_30__11.jpg",
        "2025_10_28__14_33_04__63.jpg",
        "2025_10_28__14_33_45__91.jpg",
        "2025_10_28__14_34_12__56.jpg",
        "2025_10_28__14_34_30__8.jpg",
        "2025_10_28__14_37_30__55.jpg",
        "2025_10_28__14_39_04__72.jpg",
        "2025_10_28__14_41_14__09.jpg",
        "2025_10_28__14_42_18__53.jpg",
        "2025_10_28__14_45_04__66.jpg",
        "2025_10_28__14_48_47__99.jpg",
        "2025_10_29__13_13_27__55.jpg",
        "2025_10_29__13_14_09__15.jpg",
        "2025_10_29__13_14_47__73.jpg",
        "2025_10_29__13_14_53__63.jpg",
        "2025_10_29__13_14_55__28.jpg",
        "2025_10_29__13_14_55__9.jpg",
        "2025_10_29__13_17_23__98.jpg",
        "2025_10_29__13_17_26__32.jpg",
        "2025_10_29__13_20_28__34.jpg",
        "2025_10_29__13_20_35__57.jpg",
        "2025_10_29__13_21_03__82.jpg",
        "2025_10_29__13_27_48__74.jpg",
        "2025_10_29__13_27_54__27.jpg",
        "2025_10_29__13_31_48__07.jpg",
        "2025_10_29__13_34_02__16.jpg",
        "2025_10_29__13_35_18__2.jpg",
        "2025_10_29__13_37_02__56.jpg",
        "2025_10_29__13_42_48__77.jpg",
        "2025_10_29__13_45_27__39.jpg",
        "2025_10_29__13_45_27__75.jpg",
        "2025_10_29__13_45_28__56.jpg",
        "2025_10_29__13_47_10__72.jpg",
        "2025_10_29__13_47_55__89.jpg",
        "2025_10_29__13_49_28__92.jpg",
        "2025_10_29__13_56_37__2.jpg",
        "2025_10_29__14_03_42__67.jpg",
        "2025_10_29__14_07_58__19.jpg",
        "2025_10_29__14_08_51__62.jpg",
        "2025_10_29__14_17_35__29.jpg",
        "2025_10_29__14_25_18__43.jpg",
        "2025_10_29__14_26_33__01.jpg",
        "2025_10_29__14_26_35__85.jpg",
        "2025_10_29__14_34_56__33.jpg",
        "2025_10_31__12_13_20__11.jpg",
        "2025_10_31__12_14_12__27.jpg",
        "2025_10_31__13_08_15__36.jpg",
        "2025_10_31__13_46_22__03.jpg",
        "2025_10_31__13_48_40__27.jpg",
        "2025_10_31__13_52_38__16.jpg",
        "2025_10_31__13_52_43__51.jpg",
        "2025_10_31__13_53_40__57.jpg",
        "2025_10_31__13_56_00__42.jpg",
        "2025_10_31__13_56_48__6.jpg",
        "2025_10_31__14_07_50__85.jpg",
        "2025_10_31__14_10_47__9.jpg",
        "2025_10_31__14_23_13__54.jpg",
        "2025_10_31__14_27_25__35.jpg",
        "2025_10_31__14_35_53__13.jpg",
        "2025_10_31__14_36_32__17.jpg",
        "2025_10_31__14_36_58__47.jpg",
        "2025_10_31__14_39_23__94.jpg",
        "2025_11_01__12_45_35__09.jpg",
        "2025_11_01__12_46_37__84.jpg",
        "2025_11_01__13_01_12__45.jpg",
        "2025_11_01__13_09_36__52.jpg",
        "2025_11_02__13_12_00__68.jpg",
        "2025_11_02__13_15_18__72.jpg",
        "2025_11_02__13_15_49__5.jpg",
        "2025_11_02__13_16_01__35.jpg",
        "2025_11_02__13_16_01__86.jpg",
        "2025_11_02__13_19_05__75.jpg",
        "2025_11_02__13_19_08__45.jpg",
        "2025_11_02__13_19_13__97.jpg",
        "2025_11_02__13_19_45__05.jpg",
        "2025_11_02__13_24_03__63.jpg",
        "2025_11_02__13_24_25__54.jpg",
        "2025_11_02__13_25_05__9.jpg",
        "2025_11_02__13_26_14__88.jpg",
        "2025_11_02__13_31_15__06.jpg",
        "2025_11_02__13_34_36__6.jpg",
        "2025_11_02__13_34_46__77.jpg",
        "2025_11_02__13_36_00__58.jpg",
        "2025_11_02__13_46_45__79.jpg",
        "2025_11_02__13_54_04__11.jpg",
        "2025_11_02__13_54_54__27.jpg",
        "2025_11_02__13_59_56__24.jpg",
        "2025_11_02__14_00_55__63.jpg",
        "2025_11_02__14_03_45__12.jpg",
        "2025_11_02__14_04_17__47.jpg",
        "2025_11_02__14_05_22__72.jpg",
        "2025_11_03__12_55_47__32.jpg",
        "2025_11_03__12_56_51__5.jpg",
        "2025_11_03__12_57_06__24.jpg",
        "2025_11_03__13_03_51__47.jpg",
        "2025_11_03__13_05_15__36.jpg",
        "2025_11_03__13_31_40__15.jpg",
        "2025_11_03__13_40_20__62.jpg",
        "2025_11_03__13_42_06__16.jpg",
        "2025_11_03__13_42_41__23.jpg",
        "2025_11_03__13_42_59__87.jpg",
        "2025_11_03__13_43_33__49.jpg",
        "2025_11_03__13_51_01__93.jpg",
        "2025_11_06__14_47_37__21.jpg",
        "2025_11_06__14_50_19__97.jpg",
        "2025_11_06__14_55_48__1.jpg",
        "2025_11_06__14_55_50__64.jpg",
        "2025_11_06__14_56_17__69.jpg",
        "2025_11_06__14_56_24__71.jpg",
        "2025_11_06__14_58_24__73.jpg",
        "2025_11_06__14_58_28__15.jpg",
        "2025_11_06__14_58_42__28.jpg",
        "2025_11_06__14_59_20__92.jpg",
        "2025_11_06__15_08_02__39.jpg",
        "2025_11_06__15_08_55__77.jpg",
        "2025_11_06__15_09_02__41.jpg"
    ],
    "by_filename": {
        "2024_05_20__19_51_15__09.jpg": {
            "ISO": 100,
            "aperture": 2.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2024:05:20 19:51:15",
            "file_size": "2.1 MB",
            "focal": "135.0 mm",
            "image_height": 3868,
            "image_width": 5794,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Manual",
            "shutter_speed": "1/100",
            "tags": [
                "Natur"
            ]
        },
        "2024_05_30__21_31_13__10.jpg": {
            "ISO": 200,
            "aperture": 8.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2024:05:30 21:31:13",
            "file_size": "4.0 MB",
            "focal": "135.0 mm",
            "image_height": 3509,
            "image_width": 5257,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Manual",
            "shutter_speed": 5,
            "tags": [
                "Natur",
                "Vann"
            ]
        },
        "2024_05_30__21_37_10__46.jpg": {
            "ISO": 800,
            "aperture": 3.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2024:05:30 21:37:10",
            "file_size": "4.8 MB",
            "focal": "135.0 mm",
            "image_height": 4871,
            "image_width": 3763,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Manual",
            "shutter_speed": 0.4,
            "tags": [
                "Natur",
                "Vann"
            ]
        },
        "2024_05_30__21_39_00__33.jpg": {
            "ISO": 200,
            "aperture": 9.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2024:05:30 21:39:00",
            "file_size": "3.8 MB",
            "focal": "135.0 mm",
            "image_height": 3628,
            "image_width": 4535,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Manual",
            "shutter_speed": 15,
            "tags": [
                "Natur",
                "Vann"
            ]
        },
        "2024_10_14__13_28_15__68.jpg": {
            "ISO": 100,
            "aperture": 3.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2024:10:14 13:28:15",
            "file_size": "1597 kB",
            "focal": "135.0 mm",
            "image_height": 3868,
            "image_width": 5794,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Manual",
            "shutter_speed": "1/320",
            "tags": [
                "Høst",
                "Natur"
            ]
        },
        "2025_05_26__17_44_37__86.jpg": {
            "ISO": 1600,
            "aperture": 2.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:05:26 17:44:37",
            "file_size": "1256 kB",
            "focal": "135.0 mm",
            "image_height": 1830,
            "image_width": 5490,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/2000",
            "tags": [
                "Allvi"
            ]
        },
        "2025_05_26__17_44_51__25.jpg": {
            "ISO": 1600,
            "aperture": 2.8,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:05:26 17:44:51",
            "file_size": "2.2 MB",
            "focal": "135.0 mm",
            "image_height": 3556,
            "image_width": 5327,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/2000",
            "tags": [
                "Allvi"
            ]
        },
        "2025_05_26__17_45_25__57.jpg": {
            "ISO": 1600,
            "aperture": 2.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:05:26 17:45:25",
            "file_size": "2.4 MB",
            "focal": "135.0 mm",
            "image_height": 3592,
            "image_width": 5382,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/2000",
            "tags": [
                "Allvi"
            ]
        },
        "2025_10_23__14_31_27__44.jpg": {
            "ISO": 1600,
            "aperture": 4.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:23 14:31:27",
            "file_size": "1145 kB",
            "focal": "135.0 mm",
            "image_height": 3367,
            "image_width": 5045,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/1600",
            "tags": [
                "Allvi",
                "Lade Hundepark"
            ]
        },
        "2025_10_23__14_39_57__13.jpg": {
            "ISO": 3200,
            "aperture": 5.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:23 14:39:57",
            "file_size": "2.4 MB",
            "focal": "135.0 mm",
            "image_height": 3330,
            "image_width": 3330,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/1600",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_23__14_46_23__77.jpg": {
            "ISO": 3200,
            "aperture": 4.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:23 14:46:23",
            "file_size": "3.1 MB",
            "focal": "135.0 mm",
            "image_height": 3280,
            "image_width": 5248,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/1600",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_23__14_55_24__12.jpg": {
            "ISO": 3200,
            "aperture": 2.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:23 14:55:24",
            "file_size": "3.2 MB",
            "focal": "135.0 mm",
            "image_height": 3258,
            "image_width": 5792,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/2000",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_23__14_58_44__79.jpg": {
            "ISO": 3200,
            "aperture": 2.2,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:23 14:58:44",
            "file_size": "3.1 MB",
            "focal": "135.0 mm",
            "image_height": 3356,
            "image_width": 5028,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/2000",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_23__15_07_05__43.jpg": {
            "ISO": 3200,
            "aperture": 2.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:23 15:07:05",
            "file_size": "3.4 MB",
            "focal": "135.0 mm",
            "image_height": 3320,
            "image_width": 4974,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/2000",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_23__15_17_47__46.jpg": {
            "ISO": 3200,
            "aperture": 2.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:23 15:17:47",
            "file_size": "3.0 MB",
            "focal": "135.0 mm",
            "image_height": 3275,
            "image_width": 4907,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/2000",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_23__15_26_43__11.jpg": {
            "ISO": 3200,
            "aperture": 2.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:23 15:26:43",
            "file_size": "3.2 MB",
            "focal": "135.0 mm",
            "image_height": 3696,
            "image_width": 5537,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/1000",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_28__13_57_15__56.jpg": {
            "ISO": 1600,
            "aperture": 2.2,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:28 13:57:15",
            "file_size": "1969 kB",
            "focal": "135.0 mm",
            "image_height": 3579,
            "image_width": 5362,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/2500",
            "tags": [
                "Allvi",
                "Lade Hundepark"
            ]
        },
        "2025_10_28__14_07_09__1.jpg": {
            "ISO": 3200,
            "aperture": 3.2,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:28 14:07:09",
            "file_size": "3.4 MB",
            "focal": "135.0 mm",
            "image_height": 3519,
            "image_width": 5272,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/3200",
            "tags": [
                "Allvi",
                "Lade Hundepark"
            ]
        },
        "2025_10_28__14_19_24__99.jpg": {
            "ISO": 3200,
            "aperture": 2.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:28 14:19:24",
            "file_size": "2.8 MB",
            "focal": "135.0 mm",
            "image_height": 2997,
            "image_width": 5328,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/2500",
            "tags": [
                "Fugler",
                "Lade Hundepark"
            ]
        },
        "2025_10_28__14_22_47__12.jpg": {
            "ISO": 3200,
            "aperture": 2.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:28 14:22:47",
            "file_size": "3.1 MB",
            "focal": "135.0 mm",
            "image_height": 3448,
            "image_width": 5166,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/3200",
            "tags": [
                "Allvi",
                "Lade Hundepark"
            ]
        },
        "2025_10_28__14_23_30__11.jpg": {
            "ISO": 3200,
            "aperture": 2.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:28 14:23:30",
            "file_size": "3.9 MB",
            "focal": "135.0 mm",
            "image_height": 3868,
            "image_width": 5794,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/4000",
            "tags": [
                "Allvi",
                "Lade Hundepark"
            ]
        },
        "2025_10_28__14_33_04__63.jpg": {
            "ISO": 1600,
            "aperture": 2.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:28 14:33:04",
            "file_size": "3.1 MB",
            "focal": "135.0 mm",
            "image_height": 3659,
            "image_width": 5482,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/2000",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_28__14_33_45__91.jpg": {
            "ISO": 1600,
            "aperture": 2.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:28 14:33:45",
            "file_size": "4.1 MB",
            "focal": "135.0 mm",
            "image_height": 3868,
            "image_width": 5794,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/2000",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_28__14_34_12__56.jpg": {
            "ISO": 3200,
            "aperture": 3.2,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:28 14:34:12",
            "file_size": "2.9 MB",
            "focal": "135.0 mm",
            "image_height": 3355,
            "image_width": 5027,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/2500",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_28__14_34_30__8.jpg": {
            "ISO": 3200,
            "aperture": 2.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:28 14:34:30",
            "file_size": "3.5 MB",
            "focal": "135.0 mm",
            "image_height": 3495,
            "image_width": 5592,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/2500",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_28__14_37_30__55.jpg": {
            "ISO": 3200,
            "aperture": 2.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:28 14:37:30",
            "file_size": "2.7 MB",
            "focal": "135.0 mm",
            "image_height": 3243,
            "image_width": 4858,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/3200",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_28__14_39_04__72.jpg": {
            "ISO": 3200,
            "aperture": 2.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:28 14:39:04",
            "file_size": "2.9 MB",
            "focal": "135.0 mm",
            "image_height": 3268,
            "image_width": 4896,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/3200",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_28__14_41_14__09.jpg": {
            "ISO": 3200,
            "aperture": 2.2,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:28 14:41:14",
            "file_size": "2.9 MB",
            "focal": "135.0 mm",
            "image_height": 3680,
            "image_width": 5513,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/3200",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_28__14_42_18__53.jpg": {
            "ISO": 3200,
            "aperture": 2.2,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:28 14:42:18",
            "file_size": "2.5 MB",
            "focal": "135.0 mm",
            "image_height": 3190,
            "image_width": 5104,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/3200",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_28__14_45_04__66.jpg": {
            "ISO": 3200,
            "aperture": 2.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:28 14:45:04",
            "file_size": "3.3 MB",
            "focal": "135.0 mm",
            "image_height": 3868,
            "image_width": 5794,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/3200",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_28__14_48_47__99.jpg": {
            "ISO": 3200,
            "aperture": 2.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:28 14:48:47",
            "file_size": "2.6 MB",
            "focal": "135.0 mm",
            "image_height": 3261,
            "image_width": 4886,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/3200",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_29__13_13_27__55.jpg": {
            "ISO": 1600,
            "aperture": 5.6,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:29 13:13:27",
            "file_size": "3.4 MB",
            "focal": "135.0 mm",
            "image_height": 3868,
            "image_width": 5794,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/4000",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_29__13_14_09__15.jpg": {
            "ISO": 1600,
            "aperture": 5.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:29 13:14:09",
            "file_size": "2.4 MB",
            "focal": "135.0 mm",
            "image_height": 3413,
            "image_width": 5113,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/4000",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_29__13_14_47__73.jpg": {
            "ISO": 1600,
            "aperture": 5.6,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:29 13:14:47",
            "file_size": "3.3 MB",
            "focal": "135.0 mm",
            "image_height": 3868,
            "image_width": 5794,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/4000",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_29__13_14_53__63.jpg": {
            "ISO": 1600,
            "aperture": 5.6,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:29 13:14:53",
            "file_size": "1879 kB",
            "focal": "135.0 mm",
            "image_height": 2777,
            "image_width": 4161,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/4000",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_29__13_14_55__28.jpg": {
            "ISO": 1600,
            "aperture": 4.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:29 13:14:55",
            "file_size": "2.1 MB",
            "focal": "135.0 mm",
            "image_height": 2754,
            "image_width": 4896,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/4000",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_29__13_14_55__9.jpg": {
            "ISO": 1600,
            "aperture": 4.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:29 13:14:55",
            "file_size": "2.1 MB",
            "focal": "135.0 mm",
            "image_height": 3064,
            "image_width": 4590,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/4000",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_29__13_17_23__98.jpg": {
            "ISO": 1600,
            "aperture": 8.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:29 13:17:23",
            "file_size": "2.2 MB",
            "focal": "135.0 mm",
            "image_height": 3238,
            "image_width": 4851,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/4000",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_29__13_17_26__32.jpg": {
            "ISO": 1600,
            "aperture": 9.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:29 13:17:26",
            "file_size": "2.4 MB",
            "focal": "135.0 mm",
            "image_height": 3313,
            "image_width": 4963,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/4000",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_29__13_20_28__34.jpg": {
            "ISO": 1600,
            "aperture": 6.3,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:29 13:20:28",
            "file_size": "2.6 MB",
            "focal": "135.0 mm",
            "image_height": 3487,
            "image_width": 5224,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/4000",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_29__13_20_35__57.jpg": {
            "ISO": 1600,
            "aperture": 6.3,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:29 13:20:35",
            "file_size": "2.1 MB",
            "focal": "135.0 mm",
            "image_height": 2943,
            "image_width": 5232,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/4000",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_29__13_21_03__82.jpg": {
            "ISO": 1600,
            "aperture": 7.1,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:29 13:21:03",
            "file_size": "2.3 MB",
            "focal": "135.0 mm",
            "image_height": 3359,
            "image_width": 5033,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/6400",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_29__13_27_48__74.jpg": {
            "ISO": 1600,
            "aperture": 5.6,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:29 13:27:48",
            "file_size": "1736 kB",
            "focal": "135.0 mm",
            "image_height": 3096,
            "image_width": 5504,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/5000",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_29__13_27_54__27.jpg": {
            "ISO": 1600,
            "aperture": 8.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:29 13:27:54",
            "file_size": "1735 kB",
            "focal": "135.0 mm",
            "image_height": 3171,
            "image_width": 4751,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/5000",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_29__13_31_48__07.jpg": {
            "ISO": 1600,
            "aperture": 2.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:29 13:31:48",
            "file_size": "1874 kB",
            "focal": "135.0 mm",
            "image_height": 3868,
            "image_width": 5794,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/6400",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_29__13_34_02__16.jpg": {
            "ISO": 1600,
            "aperture": 5.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:29 13:34:02",
            "file_size": "1657 kB",
            "focal": "135.0 mm",
            "image_height": 2520,
            "image_width": 4032,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/6400",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_29__13_35_18__2.jpg": {
            "ISO": 1600,
            "aperture": 2.8,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:29 13:35:18",
            "file_size": "2.6 MB",
            "focal": "135.0 mm",
            "image_height": 3515,
            "image_width": 5624,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/6400",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_29__13_37_02__56.jpg": {
            "ISO": 1600,
            "aperture": 3.2,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:29 13:37:02",
            "file_size": "1688 kB",
            "focal": "135.0 mm",
            "image_height": 3135,
            "image_width": 5016,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/6400",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_29__13_42_48__77.jpg": {
            "ISO": 1600,
            "aperture": 2.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:29 13:42:48",
            "file_size": "1881 kB",
            "focal": "135.0 mm",
            "image_height": 3840,
            "image_width": 4805,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/6400",
            "tags": [
                "Allvi",
                "Lade Hundepark"
            ]
        },
        "2025_10_29__13_45_27__39.jpg": {
            "ISO": 1600,
            "aperture": 4.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:29 13:45:27",
            "file_size": "2.0 MB",
            "focal": "135.0 mm",
            "image_height": 2982,
            "image_width": 4467,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/6400",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_29__13_45_27__75.jpg": {
            "ISO": 1600,
            "aperture": 4.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:29 13:45:27",
            "file_size": "2.0 MB",
            "focal": "135.0 mm",
            "image_height": 3142,
            "image_width": 4707,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/6400",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_29__13_45_28__56.jpg": {
            "ISO": 1600,
            "aperture": 4.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:29 13:45:28",
            "file_size": "1478 kB",
            "focal": "135.0 mm",
            "image_height": 2641,
            "image_width": 3957,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/6400",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_29__13_47_10__72.jpg": {
            "ISO": 1600,
            "aperture": 2.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:29 13:47:10",
            "file_size": "1887 kB",
            "focal": "135.0 mm",
            "image_height": 3175,
            "image_width": 5080,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/6400",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_29__13_47_55__89.jpg": {
            "ISO": 200,
            "aperture": 4.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:29 13:47:55",
            "file_size": "1266 kB",
            "focal": "135.0 mm",
            "image_height": 4830,
            "image_width": 3864,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/1600",
            "tags": [
                "Allvi",
                "Lade Hundepark"
            ]
        },
        "2025_10_29__13_49_28__92.jpg": {
            "ISO": 400,
            "aperture": 6.3,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:29 13:49:28",
            "file_size": "1657 kB",
            "focal": "135.0 mm",
            "image_height": 3864,
            "image_width": 4968,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/800",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_29__13_56_37__2.jpg": {
            "ISO": 1600,
            "aperture": 3.2,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:29 13:56:37",
            "file_size": "2.2 MB",
            "focal": "135.0 mm",
            "image_height": 3435,
            "image_width": 5496,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/4000",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_29__14_03_42__67.jpg": {
            "ISO": 1600,
            "aperture": 5.6,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:29 14:03:42",
            "file_size": "1778 kB",
            "focal": "135.0 mm",
            "image_height": 2895,
            "image_width": 4632,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/4000",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_29__14_07_58__19.jpg": {
            "ISO": 1600,
            "aperture": 2.8,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:29 14:07:58",
            "file_size": "2.1 MB",
            "focal": "135.0 mm",
            "image_height": 3511,
            "image_width": 5260,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/4000",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_29__14_08_51__62.jpg": {
            "ISO": 1600,
            "aperture": 7.1,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:29 14:08:51",
            "file_size": "2.5 MB",
            "focal": "135.0 mm",
            "image_height": 3274,
            "image_width": 4905,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/1600",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_29__14_17_35__29.jpg": {
            "ISO": 1600,
            "aperture": 2.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:29 14:17:35",
            "file_size": "2.2 MB",
            "focal": "135.0 mm",
            "image_height": 3474,
            "image_width": 5204,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/6400",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_29__14_25_18__43.jpg": {
            "ISO": 3200,
            "aperture": 4.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:29 14:25:18",
            "file_size": "2.4 MB",
            "focal": "135.0 mm",
            "image_height": 3325,
            "image_width": 4981,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/4000",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_29__14_26_33__01.jpg": {
            "ISO": 3200,
            "aperture": 3.2,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:29 14:26:33",
            "file_size": "2.7 MB",
            "focal": "135.0 mm",
            "image_height": 3631,
            "image_width": 5439,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/4000",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_29__14_26_35__85.jpg": {
            "ISO": 3200,
            "aperture": 2.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:29 14:26:35",
            "file_size": "2.6 MB",
            "focal": "135.0 mm",
            "image_height": 3528,
            "image_width": 5286,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/4000",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_29__14_34_56__33.jpg": {
            "ISO": 1600,
            "aperture": 7.1,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:29 14:34:56",
            "file_size": "5.4 MB",
            "focal": "135.0 mm",
            "image_height": 3718,
            "image_width": 5570,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/500",
            "tags": [
                "Høst",
                "Natur"
            ]
        },
        "2025_10_31__12_13_20__11.jpg": {
            "ISO": 800,
            "aperture": 2.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:31 12:13:20",
            "file_size": "1660 kB",
            "focal": "135.0 mm",
            "image_height": 3538,
            "image_width": 5301,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Manual",
            "shutter_speed": "1/1000",
            "tags": [
                "Høst",
                "Natur"
            ]
        },
        "2025_10_31__12_14_12__27.jpg": {
            "ISO": 400,
            "aperture": 2.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:31 12:14:12",
            "file_size": "2.2 MB",
            "focal": "135.0 mm",
            "image_height": 3602,
            "image_width": 5396,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Manual",
            "shutter_speed": "1/1000",
            "tags": [
                "Høst",
                "Natur"
            ]
        },
        "2025_10_31__13_08_15__36.jpg": {
            "ISO": 1600,
            "aperture": 2.8,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:31 13:08:15",
            "file_size": "3.1 MB",
            "focal": "50.0 mm",
            "image_height": 3868,
            "image_width": 5794,
            "lens": "Sigma 50mm f/1.4 DG HSM | A or Zeiss Milvus 50mm f/1.4 or Sigma 50mm f/1.5 FF High-Speed Prime | 017 or Tokina Opera 50mm f/1.4 FF",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/1250",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_31__13_46_22__03.jpg": {
            "ISO": 3200,
            "aperture": 1.8,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:31 13:46:22",
            "file_size": "2.2 MB",
            "focal": "50.0 mm",
            "image_height": 3372,
            "image_width": 5052,
            "lens": "Sigma 50mm f/1.4 DG HSM | A or Zeiss Milvus 50mm f/1.4 or Sigma 50mm f/1.5 FF High-Speed Prime | 017 or Tokina Opera 50mm f/1.4 FF",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/3200",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_31__13_48_40__27.jpg": {
            "ISO": 3200,
            "aperture": 2.8,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:31 13:48:40",
            "file_size": "2.1 MB",
            "focal": "50.0 mm",
            "image_height": 3169,
            "image_width": 4747,
            "lens": "Sigma 50mm f/1.4 DG HSM | A or Zeiss Milvus 50mm f/1.4 or Sigma 50mm f/1.5 FF High-Speed Prime | 017 or Tokina Opera 50mm f/1.4 FF",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/3200",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_31__13_52_38__16.jpg": {
            "ISO": 1600,
            "aperture": 2.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:31 13:52:38",
            "file_size": "1833 kB",
            "focal": "50.0 mm",
            "image_height": 2938,
            "image_width": 4402,
            "lens": "Sigma 50mm f/1.4 DG HSM | A or Zeiss Milvus 50mm f/1.4 or Sigma 50mm f/1.5 FF High-Speed Prime | 017 or Tokina Opera 50mm f/1.4 FF",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/2500",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_31__13_52_43__51.jpg": {
            "ISO": 1600,
            "aperture": 2.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:31 13:52:43",
            "file_size": "2.7 MB",
            "focal": "50.0 mm",
            "image_height": 3573,
            "image_width": 5353,
            "lens": "Sigma 50mm f/1.4 DG HSM | A or Zeiss Milvus 50mm f/1.4 or Sigma 50mm f/1.5 FF High-Speed Prime | 017 or Tokina Opera 50mm f/1.4 FF",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/2500",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_31__13_53_40__57.jpg": {
            "ISO": 1600,
            "aperture": 2.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:31 13:53:40",
            "file_size": "1970 kB",
            "focal": "50.0 mm",
            "image_height": 3020,
            "image_width": 4524,
            "lens": "Sigma 50mm f/1.4 DG HSM | A or Zeiss Milvus 50mm f/1.4 or Sigma 50mm f/1.5 FF High-Speed Prime | 017 or Tokina Opera 50mm f/1.4 FF",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/2500",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_31__13_56_00__42.jpg": {
            "ISO": 1600,
            "aperture": 2.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:31 13:56:00",
            "file_size": "2.3 MB",
            "focal": "50.0 mm",
            "image_height": 3620,
            "image_width": 4525,
            "lens": "Sigma 50mm f/1.4 DG HSM | A or Zeiss Milvus 50mm f/1.4 or Sigma 50mm f/1.5 FF High-Speed Prime | 017 or Tokina Opera 50mm f/1.4 FF",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/2500",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_31__13_56_48__6.jpg": {
            "ISO": 1600,
            "aperture": 2.2,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:31 13:56:48",
            "file_size": "2.7 MB",
            "focal": "50.0 mm",
            "image_height": 3525,
            "image_width": 5640,
            "lens": "Sigma 50mm f/1.4 DG HSM | A or Zeiss Milvus 50mm f/1.4 or Sigma 50mm f/1.5 FF High-Speed Prime | 017 or Tokina Opera 50mm f/1.4 FF",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/2500",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_31__14_07_50__85.jpg": {
            "ISO": 3200,
            "aperture": 3.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:31 14:07:50",
            "file_size": "3.2 MB",
            "focal": "50.0 mm",
            "image_height": 3024,
            "image_width": 5376,
            "lens": "Sigma 50mm f/1.4 DG HSM | A or Zeiss Milvus 50mm f/1.4 or Sigma 50mm f/1.5 FF High-Speed Prime | 017 or Tokina Opera 50mm f/1.4 FF",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/1250",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_31__14_10_47__9.jpg": {
            "ISO": 3200,
            "aperture": 2.8,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:31 14:10:47",
            "file_size": "2.5 MB",
            "focal": "50.0 mm",
            "image_height": 3030,
            "image_width": 4848,
            "lens": "Sigma 50mm f/1.4 DG HSM | A or Zeiss Milvus 50mm f/1.4 or Sigma 50mm f/1.5 FF High-Speed Prime | 017 or Tokina Opera 50mm f/1.4 FF",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/1250",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_31__14_23_13__54.jpg": {
            "ISO": 1600,
            "aperture": 1.4,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:31 14:23:13",
            "file_size": "2.7 MB",
            "focal": "50.0 mm",
            "image_height": 3620,
            "image_width": 5792,
            "lens": "Sigma 50mm f/1.4 DG HSM | A or Zeiss Milvus 50mm f/1.4 or Sigma 50mm f/1.5 FF High-Speed Prime | 017 or Tokina Opera 50mm f/1.4 FF",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/1600",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_31__14_27_25__35.jpg": {
            "ISO": 1600,
            "aperture": 1.4,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:31 14:27:25",
            "file_size": "2.1 MB",
            "focal": "50.0 mm",
            "image_height": 3101,
            "image_width": 4646,
            "lens": "Sigma 50mm f/1.4 DG HSM | A or Zeiss Milvus 50mm f/1.4 or Sigma 50mm f/1.5 FF High-Speed Prime | 017 or Tokina Opera 50mm f/1.4 FF",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/2500",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_31__14_35_53__13.jpg": {
            "ISO": 3200,
            "aperture": 2.2,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:31 14:35:53",
            "file_size": "2.3 MB",
            "focal": "50.0 mm",
            "image_height": 3301,
            "image_width": 4945,
            "lens": "Sigma 50mm f/1.4 DG HSM | A or Zeiss Milvus 50mm f/1.4 or Sigma 50mm f/1.5 FF High-Speed Prime | 017 or Tokina Opera 50mm f/1.4 FF",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/2000",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_31__14_36_32__17.jpg": {
            "ISO": 3200,
            "aperture": 1.4,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:31 14:36:32",
            "file_size": "2.7 MB",
            "focal": "50.0 mm",
            "image_height": 3285,
            "image_width": 5256,
            "lens": "Sigma 50mm f/1.4 DG HSM | A or Zeiss Milvus 50mm f/1.4 or Sigma 50mm f/1.5 FF High-Speed Prime | 017 or Tokina Opera 50mm f/1.4 FF",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/2000",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_31__14_36_58__47.jpg": {
            "ISO": 3200,
            "aperture": 1.4,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:31 14:36:58",
            "file_size": "2.7 MB",
            "focal": "50.0 mm",
            "image_height": 3325,
            "image_width": 5320,
            "lens": "Sigma 50mm f/1.4 DG HSM | A or Zeiss Milvus 50mm f/1.4 or Sigma 50mm f/1.5 FF High-Speed Prime | 017 or Tokina Opera 50mm f/1.4 FF",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/1600",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_10_31__14_39_23__94.jpg": {
            "ISO": 3200,
            "aperture": 2.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:10:31 14:39:23",
            "file_size": "3.2 MB",
            "focal": "50.0 mm",
            "image_height": 3864,
            "image_width": 4830,
            "lens": "Sigma 50mm f/1.4 DG HSM | A or Zeiss Milvus 50mm f/1.4 or Sigma 50mm f/1.5 FF High-Speed Prime | 017 or Tokina Opera 50mm f/1.4 FF",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/1600",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_11_01__12_45_35__09.jpg": {
            "ISO": 3200,
            "aperture": 4.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:01 12:45:35",
            "file_size": "3.1 MB",
            "focal": "135.0 mm",
            "image_height": 3674,
            "image_width": 5504,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/2500",
            "tags": [
                "Allvi"
            ]
        },
        "2025_11_01__12_46_37__84.jpg": {
            "ISO": 3200,
            "aperture": 2.8,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:01 12:46:37",
            "file_size": "2.5 MB",
            "focal": "135.0 mm",
            "image_height": 3867,
            "image_width": 5793,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/2500",
            "tags": [
                "Allvi"
            ]
        },
        "2025_11_01__13_01_12__45.jpg": {
            "ISO": 3200,
            "aperture": 5.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:01 13:01:12",
            "file_size": "2.7 MB",
            "focal": "135.0 mm",
            "image_height": 3627,
            "image_width": 5433,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/3200",
            "tags": [
                "Allvi"
            ]
        },
        "2025_11_01__13_09_36__52.jpg": {
            "ISO": 800,
            "aperture": 5.6,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:01 13:09:36",
            "file_size": "2.6 MB",
            "focal": "135.0 mm",
            "image_height": 3687,
            "image_width": 5523,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/1250",
            "tags": [
                "Høst",
                "Natur"
            ]
        },
        "2025_11_02__13_12_00__68.jpg": {
            "ISO": 1600,
            "aperture": 4.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:02 13:12:00",
            "file_size": "2.1 MB",
            "focal": "135.0 mm",
            "image_height": 3315,
            "image_width": 4966,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/2000",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_11_02__13_15_18__72.jpg": {
            "ISO": 1600,
            "aperture": 3.2,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:02 13:15:18",
            "file_size": "1702 kB",
            "focal": "135.0 mm",
            "image_height": 3440,
            "image_width": 5504,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/2000",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_11_02__13_15_49__5.jpg": {
            "ISO": 1600,
            "aperture": 4.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:02 13:15:49",
            "file_size": "2.7 MB",
            "focal": "135.0 mm",
            "image_height": 2988,
            "image_width": 5312,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/2000",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_11_02__13_16_01__35.jpg": {
            "ISO": 1600,
            "aperture": 3.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:02 13:16:01",
            "file_size": "2.4 MB",
            "focal": "135.0 mm",
            "image_height": 3430,
            "image_width": 5138,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/2000",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_11_02__13_16_01__86.jpg": {
            "ISO": 1600,
            "aperture": 3.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:02 13:16:01",
            "file_size": "2.6 MB",
            "focal": "135.0 mm",
            "image_height": 3642,
            "image_width": 5650,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/2000",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_11_02__13_19_05__75.jpg": {
            "ISO": 1600,
            "aperture": 3.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:02 13:19:05",
            "file_size": "2.5 MB",
            "focal": "135.0 mm",
            "image_height": 3405,
            "image_width": 5448,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/2000",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_11_02__13_19_08__45.jpg": {
            "ISO": 1600,
            "aperture": 4.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:02 13:19:08",
            "file_size": "2.6 MB",
            "focal": "135.0 mm",
            "image_height": 3485,
            "image_width": 5576,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/2000",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_11_02__13_19_13__97.jpg": {
            "ISO": 1600,
            "aperture": 3.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:02 13:19:13",
            "file_size": "2.2 MB",
            "focal": "135.0 mm",
            "image_height": 3494,
            "image_width": 5235,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/2000",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_11_02__13_19_45__05.jpg": {
            "ISO": 1600,
            "aperture": 2.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:02 13:19:45",
            "file_size": "1946 kB",
            "focal": "135.0 mm",
            "image_height": 3674,
            "image_width": 5504,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/2000",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_11_02__13_24_03__63.jpg": {
            "ISO": 1600,
            "aperture": 5.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:02 13:24:03",
            "file_size": "1806 kB",
            "focal": "135.0 mm",
            "image_height": 2800,
            "image_width": 4480,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/1250",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_11_02__13_24_25__54.jpg": {
            "ISO": 1600,
            "aperture": 5.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:02 13:24:25",
            "file_size": "2.6 MB",
            "focal": "135.0 mm",
            "image_height": 3222,
            "image_width": 5728,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/1250",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_11_02__13_25_05__9.jpg": {
            "ISO": 1600,
            "aperture": 4.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:02 13:25:05",
            "file_size": "2.2 MB",
            "focal": "135.0 mm",
            "image_height": 3087,
            "image_width": 5488,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/1250",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_11_02__13_26_14__88.jpg": {
            "ISO": 1600,
            "aperture": 3.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:02 13:26:14",
            "file_size": "1840 kB",
            "focal": "135.0 mm",
            "image_height": 2880,
            "image_width": 5120,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/2000",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_11_02__13_31_15__06.jpg": {
            "ISO": 1600,
            "aperture": 4.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:02 13:31:15",
            "file_size": "1922 kB",
            "focal": "135.0 mm",
            "image_height": 3085,
            "image_width": 4936,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/2000",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_11_02__13_34_36__6.jpg": {
            "ISO": 1600,
            "aperture": 3.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:02 13:34:36",
            "file_size": "2.3 MB",
            "focal": "135.0 mm",
            "image_height": 3524,
            "image_width": 5279,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/2500",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_11_02__13_34_46__77.jpg": {
            "ISO": 1600,
            "aperture": 3.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:02 13:34:46",
            "file_size": "1885 kB",
            "focal": "135.0 mm",
            "image_height": 3125,
            "image_width": 5000,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/2500",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_11_02__13_36_00__58.jpg": {
            "ISO": 1600,
            "aperture": 3.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:02 13:36:00",
            "file_size": "1453 kB",
            "focal": "135.0 mm",
            "image_height": 3108,
            "image_width": 4657,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/3200",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_11_02__13_46_45__79.jpg": {
            "ISO": 1600,
            "aperture": 4.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:02 13:46:45",
            "file_size": "2.3 MB",
            "focal": "135.0 mm",
            "image_height": 3868,
            "image_width": 5794,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/3200",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_11_02__13_54_04__11.jpg": {
            "ISO": 1600,
            "aperture": 3.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:02 13:54:04",
            "file_size": "1919 kB",
            "focal": "135.0 mm",
            "image_height": 3078,
            "image_width": 5472,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/3200",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_11_02__13_54_54__27.jpg": {
            "ISO": 1600,
            "aperture": 4.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:02 13:54:54",
            "file_size": "1970 kB",
            "focal": "135.0 mm",
            "image_height": 3188,
            "image_width": 4776,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/3200",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_11_02__13_59_56__24.jpg": {
            "ISO": 1600,
            "aperture": 2.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:02 13:59:56",
            "file_size": "1728 kB",
            "focal": "135.0 mm",
            "image_height": 3321,
            "image_width": 4976,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/3200",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_11_02__14_00_55__63.jpg": {
            "ISO": 1600,
            "aperture": 2.8,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:02 14:00:55",
            "file_size": "2.5 MB",
            "focal": "135.0 mm",
            "image_height": 3868,
            "image_width": 5794,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/3200",
            "tags": [
                "Allvi",
                "Lade Hundepark"
            ]
        },
        "2025_11_02__14_03_45__12.jpg": {
            "ISO": 1600,
            "aperture": 2.8,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:02 14:03:45",
            "file_size": "2.1 MB",
            "focal": "135.0 mm",
            "image_height": 3762,
            "image_width": 5636,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/3200",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_11_02__14_04_17__47.jpg": {
            "ISO": 1600,
            "aperture": 2.8,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:02 14:04:17",
            "file_size": "2.1 MB",
            "focal": "135.0 mm",
            "image_height": 3501,
            "image_width": 5245,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/3200",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_11_02__14_05_22__72.jpg": {
            "ISO": 1600,
            "aperture": 2.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:02 14:05:22",
            "file_size": "2.2 MB",
            "focal": "135.0 mm",
            "image_height": 3612,
            "image_width": 5411,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/3200",
            "tags": [
                "Lade Hundepark"
            ]
        },
        "2025_11_03__12_55_47__32.jpg": {
            "ISO": 1600,
            "aperture": 3.2,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:03 12:55:47",
            "file_size": "2.1 MB",
            "focal": "135.0 mm",
            "image_height": 3341,
            "image_width": 5006,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/3200",
            "tags": [
                "Nordbyen Hundepark"
            ]
        },
        "2025_11_03__12_56_51__5.jpg": {
            "ISO": 1600,
            "aperture": 3.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:03 12:56:51",
            "file_size": "1657 kB",
            "focal": "135.0 mm",
            "image_height": 3291,
            "image_width": 4930,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/3200",
            "tags": [
                "Nordbyen Hundepark"
            ]
        },
        "2025_11_03__12_57_06__24.jpg": {
            "ISO": 1600,
            "aperture": 3.2,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:03 12:57:06",
            "file_size": "1536 kB",
            "focal": "135.0 mm",
            "image_height": 2709,
            "image_width": 4816,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/3200",
            "tags": [
                "Nordbyen Hundepark"
            ]
        },
        "2025_11_03__13_03_51__47.jpg": {
            "ISO": 1600,
            "aperture": 3.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:03 13:03:51",
            "file_size": "1938 kB",
            "focal": "135.0 mm",
            "image_height": 3356,
            "image_width": 5028,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/3200",
            "tags": [
                "Nordbyen Hundepark"
            ]
        },
        "2025_11_03__13_05_15__36.jpg": {
            "ISO": 1600,
            "aperture": 3.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:03 13:05:15",
            "file_size": "2.3 MB",
            "focal": "135.0 mm",
            "image_height": 3620,
            "image_width": 5792,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/3200",
            "tags": [
                "Nordbyen Hundepark"
            ]
        },
        "2025_11_03__13_31_40__15.jpg": {
            "ISO": 3200,
            "aperture": 4.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:03 13:31:40",
            "file_size": "2.2 MB",
            "focal": "135.0 mm",
            "image_height": 3426,
            "image_width": 5132,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/5000",
            "tags": [
                "Nordbyen Hundepark"
            ]
        },
        "2025_11_03__13_40_20__62.jpg": {
            "ISO": 3200,
            "aperture": 4.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:03 13:40:20",
            "file_size": "2.4 MB",
            "focal": "135.0 mm",
            "image_height": 3352,
            "image_width": 5022,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/5000",
            "tags": [
                "Nordbyen Hundepark"
            ]
        },
        "2025_11_03__13_42_06__16.jpg": {
            "ISO": 3200,
            "aperture": 3.2,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:03 13:42:06",
            "file_size": "2.5 MB",
            "focal": "135.0 mm",
            "image_height": 3258,
            "image_width": 5792,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/5000",
            "tags": [
                "Nordbyen Hundepark"
            ]
        },
        "2025_11_03__13_42_41__23.jpg": {
            "ISO": 3200,
            "aperture": 4.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:03 13:42:41",
            "file_size": "3.1 MB",
            "focal": "135.0 mm",
            "image_height": 3695,
            "image_width": 5536,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/5000",
            "tags": [
                "Nordbyen Hundepark"
            ]
        },
        "2025_11_03__13_42_59__87.jpg": {
            "ISO": 3200,
            "aperture": 3.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:03 13:42:59",
            "file_size": "2.1 MB",
            "focal": "135.0 mm",
            "image_height": 3640,
            "image_width": 4555,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/3200",
            "tags": [
                "Nordbyen Hundepark"
            ]
        },
        "2025_11_03__13_43_33__49.jpg": {
            "ISO": 3200,
            "aperture": 4.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:03 13:43:33",
            "file_size": "2.1 MB",
            "focal": "135.0 mm",
            "image_height": 3146,
            "image_width": 4713,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/4000",
            "tags": [
                "Nordbyen Hundepark"
            ]
        },
        "2025_11_03__13_51_01__93.jpg": {
            "ISO": 3200,
            "aperture": 3.2,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:03 13:51:01",
            "file_size": "2.8 MB",
            "focal": "135.0 mm",
            "image_height": 3703,
            "image_width": 5548,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/3200",
            "tags": [
                "Nordbyen Hundepark"
            ]
        },
        "2025_11_06__14_47_37__21.jpg": {
            "ISO": 1600,
            "aperture": 2.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:06 14:47:37",
            "file_size": "1997 kB",
            "focal": "135.0 mm",
            "image_height": 3528,
            "image_width": 4410,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/1600",
            "tags": [
                "Nordbyen Hundepark"
            ]
        },
        "2025_11_06__14_50_19__97.jpg": {
            "ISO": 3200,
            "aperture": 2.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:06 14:50:19",
            "file_size": "2.4 MB",
            "focal": "135.0 mm",
            "image_height": 3227,
            "image_width": 4834,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/2500",
            "tags": [
                "Nordbyen Hundepark"
            ]
        },
        "2025_11_06__14_55_48__1.jpg": {
            "ISO": 1600,
            "aperture": 2.8,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:06 14:55:48",
            "file_size": "2.2 MB",
            "focal": "135.0 mm",
            "image_height": 3227,
            "image_width": 4834,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/1250",
            "tags": [
                "Nordbyen Hundepark"
            ]
        },
        "2025_11_06__14_55_50__64.jpg": {
            "ISO": 1600,
            "aperture": 2.8,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:06 14:55:50",
            "file_size": "2.4 MB",
            "focal": "135.0 mm",
            "image_height": 3227,
            "image_width": 4834,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/1250",
            "tags": [
                "Nordbyen Hundepark"
            ]
        },
        "2025_11_06__14_56_17__69.jpg": {
            "ISO": 3200,
            "aperture": 2.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:06 14:56:17",
            "file_size": "2.6 MB",
            "focal": "135.0 mm",
            "image_height": 3227,
            "image_width": 4834,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/1600",
            "tags": [
                "Nordbyen Hundepark"
            ]
        },
        "2025_11_06__14_56_24__71.jpg": {
            "ISO": 3200,
            "aperture": 2.8,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:06 14:56:24",
            "file_size": "2.7 MB",
            "focal": "135.0 mm",
            "image_height": 3227,
            "image_width": 4834,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/1600",
            "tags": [
                "Nordbyen Hundepark"
            ]
        },
        "2025_11_06__14_58_24__73.jpg": {
            "ISO": 3200,
            "aperture": 2.8,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:06 14:58:24",
            "file_size": "2.4 MB",
            "focal": "135.0 mm",
            "image_height": 3227,
            "image_width": 4834,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/1600",
            "tags": [
                "Nordbyen Hundepark"
            ]
        },
        "2025_11_06__14_58_28__15.jpg": {
            "ISO": 3200,
            "aperture": 3.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:06 14:58:28",
            "file_size": "2.6 MB",
            "focal": "135.0 mm",
            "image_height": 3227,
            "image_width": 4834,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/1600",
            "tags": [
                "Nordbyen Hundepark"
            ]
        },
        "2025_11_06__14_58_42__28.jpg": {
            "ISO": 3200,
            "aperture": 4.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:06 14:58:42",
            "file_size": "3.7 MB",
            "focal": "135.0 mm",
            "image_height": 3558,
            "image_width": 5331,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/1250",
            "tags": [
                "Nordbyen Hundepark"
            ]
        },
        "2025_11_06__14_59_20__92.jpg": {
            "ISO": 1600,
            "aperture": 2.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:06 14:59:20",
            "file_size": "1903 kB",
            "focal": "135.0 mm",
            "image_height": 3227,
            "image_width": 4834,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/1000",
            "tags": [
                "Nordbyen Hundepark"
            ]
        },
        "2025_11_06__15_08_02__39.jpg": {
            "ISO": 3200,
            "aperture": 2.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:06 15:08:02",
            "file_size": "2.3 MB",
            "focal": "135.0 mm",
            "image_height": 3173,
            "image_width": 4753,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/2000",
            "tags": [
                "Nordbyen Hundepark"
            ]
        },
        "2025_11_06__15_08_55__77.jpg": {
            "ISO": 1600,
            "aperture": 2.5,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:06 15:08:55",
            "file_size": "2.2 MB",
            "focal": "135.0 mm",
            "image_height": 3512,
            "image_width": 5262,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/800",
            "tags": [
                "Nordbyen Hundepark"
            ]
        },
        "2025_11_06__15_09_02__41.jpg": {
            "ISO": 1600,
            "aperture": 2.0,
            "camera": "Canon EOS 5D Mark III",
            "capture_time": "2025:11:06 15:09:02",
            "file_size": "3.0 MB",
            "focal": "135.0 mm",
            "image_height": 3868,
            "image_width": 5794,
            "lens": "Canon EF 135mm f/2L USM",
            "shooting_mode": "Shutter speed priority AE",
            "shutter_speed": "1/800",
            "tags": [
                "Nordbyen Hundepark"
            ]
        }
    },
    "by_rating": {
        "-1": [
            "2024_05_20__19_51_15__09.jpg",
            "2024_05_30__21_31_13__10.jpg",
            "2024_05_30__21_37_10__46.jpg",
            "2024_05_30__21_39_00__33.jpg",
            "2024_10_14__13_28_15__68.jpg",
            "2025_05_26__17_44_37__86.jpg",
            "2025_05_26__17_44_51__25.jpg",
            "2025_05_26__17_45_25__57.jpg",
            "2025_10_23__14_31_27__44.jpg",
            "2025_10_23__14_39_57__13.jpg",
            "2025_10_23__14_46_23__77.jpg",
            "2025_10_23__14_55_24__12.jpg",
            "2025_10_23__14_58_44__79.jpg",
            "2025_10_23__15_07_05__43.jpg",
            "2025_10_23__15_17_47__46.jpg",
            "2025_10_23__15_26_43__11.jpg",
            "2025_10_28__14_07_09__1.jpg",
            "2025_10_28__14_19_24__99.jpg",
            "2025_10_28__14_22_47__12.jpg",
            "2025_10_28__14_23_30__11.jpg",
            "2025_10_28__14_33_04__63.jpg",
            "2025_10_28__14_33_45__91.jpg",
            "2025_10_28__14_34_12__56.jpg",
            "2025_10_28__14_34_30__8.jpg",
            "2025_10_28__14_37_30__55.jpg",
            "2025_10_28__14_39_04__72.jpg",
            "2025_10_28__14_41_14__09.jpg",
            "2025_10_28__14_42_18__53.jpg",
            "2025_10_28__14_45_04__66.jpg",
            "2025_10_28__14_48_47__99.jpg",
            "2025_10_29__13_13_27__55.jpg",
            "2025_10_29__13_14_09__15.jpg",
            "2025_10_29__13_14_47__73.jpg",
            "2025_10_29__13_14_53__63.jpg",
            "2025_10_29__13_14_55__28.jpg",
            "2025_10_29__13_14_55__9.jpg",
            "2025_10_29__13_17_23__98.jpg",
            "2025_10_29__13_17_26__32.jpg",
            "2025_10_29__13_20_28__34.jpg",
            "2025_10_29__13_20_35__57.jpg",
            "2025_10_29__13_21_03__82.jpg",
            "2025_10_29__13_27_48__74.jpg",
            "2025_10_29__13_27_54__27.jpg",
            "2025_10_29__13_31_48__07.jpg",
            "2025_10_29__13_34_02__16.jpg",
            "2025_10_29__13_35_18__2.jpg",
            "2025_10_29__13_37_02__56.jpg",
            "2025_10_29__13_42_48__77.jpg",
            "2025_10_29__13_45_27__39.jpg",
            "2025_10_29__13_45_27__75.jpg",
            "2025_10_29__13_45_28__56.jpg",
            "2025_10_29__13_47_10__72.jpg",
            "2025_10_29__13_47_55__89.jpg",
            "2025_10_29__13_49_28__92.jpg",
            "2025_10_29__13_56_37__2.jpg",
            "2025_10_29__14_03_42__67.jpg",
            "2025_10_29__14_07_58__19.jpg",
            "2025_10_29__14_08_51__62.jpg",
            "2025_10_29__14_17_35__29.jpg",
            "2025_10_29__14_25_18__43.jpg",
            "2025_10_29__14_26_33__01.jpg",
            "2025_10_29__14_26_35__85.jpg",
            "2025_10_29__14_34_56__33.jpg",
            "2025_10_31__12_13_20__11.jpg",
            "2025_10_31__12_14_12__27.jpg",
            "2025_10_31__13_08_15__36.jpg",
            "2025_10_31__13_46_22__03.jpg",
            "2025_10_31__13_48_40__27.jpg",
            "2025_10_31__13_52_38__16.jpg",
            "2025_10_31__13_52_43__51.jpg",
            "2025_10_31__13_53_40__57.jpg",
            "2025_10_31__13_56_00__42.jpg",
            "2025_10_31__13_56_48__6.jpg",
            "2025_10_31__14_07_50__85.jpg",
            "2025_10_31__14_10_47__9.jpg",
            "2025_10_31__14_23_13__54.jpg",
            "2025_10_31__14_27_25__35.jpg",
            "2025_10_31__14_35_53__13.jpg",
            "2025_10_31__14_36_32__17.jpg",
            "2025_10_31__14_36_58__47.jpg",
            "2025_10_31__14_39_23__94.jpg",
            "2025_11_01__12_45_35__09.jpg",
            "2025_11_01__12_46_37__84.jpg",
            "2025_11_01__13_01_12__45.jpg",
            "2025_11_01__13_09_36__52.jpg",
            "2025_11_02__13_12_00__68.jpg",
            "2025_11_02__13_15_18__72.jpg",
            "2025_11_02__13_15_49__5.jpg",
            "2025_11_02__13_16_01__35.jpg",
            "2025_11_02__13_16_01__86.jpg",
            "2025_11_02__13_19_05__75.jpg",
            "2025_11_02__13_19_08__45.jpg",
            "2025_11_02__13_19_13__97.jpg",
            "2025_11_02__13_19_45__05.jpg",
            "2025_11_02__13_24_03__63.jpg",
            "2025_11_02__13_24_25__54.jpg",
            "2025_11_02__13_25_05__9.jpg",
            "2025_11_02__13_26_14__88.jpg",
            "2025_11_02__13_31_15__06.jpg",
            "2025_11_02__13_34_36__6.jpg",
            "2025_11_02__13_34_46__77.jpg",
            "2025_11_02__13_36_00__58.jpg",
            "2025_11_02__13_46_45__79.jpg",
            "2025_11_02__13_54_04__11.jpg",
            "2025_11_02__13_54_54__27.jpg",
            "2025_11_02__13_59_56__24.jpg",
            "2025_11_02__14_00_55__63.jpg",
            "2025_11_02__14_03_45__12.jpg",
            "2025_11_02__14_04_17__47.jpg",
            "2025_11_02__14_05_22__72.jpg",
            "2025_11_03__12_55_47__32.jpg",
            "2025_11_03__12_56_51__5.jpg",
            "2025_11_03__12_57_06__24.jpg",
            "2025_11_03__13_03_51__47.jpg",
            "2025_11_03__13_05_15__36.jpg",
            "2025_11_03__13_31_40__15.jpg",
            "2025_11_03__13_40_20__62.jpg",
            "2025_11_03__13_42_06__16.jpg",
            "2025_11_03__13_42_41__23.jpg",
            "2025_11_03__13_42_59__87.jpg",
            "2025_11_03__13_43_33__49.jpg",
            "2025_11_03__13_51_01__93.jpg",
            "2025_11_06__14_47_37__21.jpg",
            "2025_11_06__14_50_19__97.jpg",
            "2025_11_06__14_55_48__1.jpg",
            "2025_11_06__14_55_50__64.jpg",
            "2025_11_06__14_56_17__69.jpg",
            "2025_11_06__14_56_24__71.jpg",
            "2025_11_06__14_58_24__73.jpg",
            "2025_11_06__14_58_28__15.jpg",
            "2025_11_06__14_58_42__28.jpg",
            "2025_11_06__14_59_20__92.jpg",
            "2025_11_06__15_08_02__39.jpg",
            "2025_11_06__15_08_55__77.jpg",
            "2025_11_06__15_09_02__41.jpg"
        ],
        "3": [
            "2025_10_28__13_57_15__56.jpg"
        ]
    },
    "by_tag": {
        "Allvi": [
            "2025_05_26__17_44_37__86.jpg",
            "2025_05_26__17_44_51__25.jpg",
            "2025_05_26__17_45_25__57.jpg",
            "2025_10_23__14_31_27__44.jpg",
            "2025_10_28__13_57_15__56.jpg",
            "2025_10_28__14_07_09__1.jpg",
            "2025_10_28__14_22_47__12.jpg",
            "2025_10_28__14_23_30__11.jpg",
            "2025_10_29__13_42_48__77.jpg",
            "2025_10_29__13_47_55__89.jpg",
            "2025_11_01__12_45_35__09.jpg",
            "2025_11_01__12_46_37__84.jpg",
            "2025_11_01__13_01_12__45.jpg",
            "2025_11_02__14_00_55__63.jpg"
        ],
        "Fugler": [
            "2025_10_28__14_19_24__99.jpg"
        ],
        "Høst": [
            "2024_10_14__13_28_15__68.jpg",
            "2025_10_29__14_34_56__33.jpg",
            "2025_10_31__12_13_20__11.jpg",
            "2025_10_31__12_14_12__27.jpg",
            "2025_11_01__13_09_36__52.jpg"
        ],
        "Lade Hundepark": [
            "2025_10_23__14_31_27__44.jpg",
            "2025_10_23__14_39_57__13.jpg",
            "2025_10_23__14_46_23__77.jpg",
            "2025_10_23__14_55_24__12.jpg",
            "2025_10_23__14_58_44__79.jpg",
            "2025_10_23__15_07_05__43.jpg",
            "2025_10_23__15_17_47__46.jpg",
            "2025_10_23__15_26_43__11.jpg",
            "2025_10_28__13_57_15__56.jpg",
            "2025_10_28__14_07_09__1.jpg",
            "2025_10_28__14_19_24__99.jpg",
            "2025_10_28__14_22_47__12.jpg",
            "2025_10_28__14_23_30__11.jpg",
            "2025_10_28__14_33_04__63.jpg",
            "2025_10_28__14_33_45__91.jpg",
            "2025_10_28__14_34_12__56.jpg",
            "2025_10_28__14_34_30__8.jpg",
            "2025_10_28__14_37_30__55.jpg",
            "2025_10_28__14_39_04__72.jpg",
            "2025_10_28__14_41_14__09.jpg",
            "2025_10_28__14_42_18__53.jpg",
            "2025_10_28__14_45_04__66.jpg",
            "2025_10_28__14_48_47__99.jpg",
            "2025_10_29__13_13_27__55.jpg",
            "2025_10_29__13_14_09__15.jpg",
            "2025_10_29__13_14_47__73.jpg",
            "2025_10_29__13_14_53__63.jpg",
            "2025_10_29__13_14_55__28.jpg",
            "2025_10_29__13_14_55__9.jpg",
            "2025_10_29__13_17_23__98.jpg",
            "2025_10_29__13_17_26__32.jpg",
            "2025_10_29__13_20_28__34.jpg",
            "2025_10_29__13_20_35__57.jpg",
            "2025_10_29__13_21_03__82.jpg",
            "2025_10_29__13_27_48__74.jpg",
            "2025_10_29__13_27_54__27.jpg",
            "2025_10_29__13_31_48__07.jpg",
            "2025_10_29__13_34_02__16.jpg",
            "2025_10_29__13_35_18__2.jpg",
            "2025_10_29__13_37_02__56.jpg",
            "2025_10_29__13_42_48__77.jpg",
            "2025_10_29__13_45_27__39.jpg",
            "2025_10_29__13_45_27__75.jpg",
            "2025_10_29__13_45_28__56.jpg",
            "2025_10_29__13_47_10__72.jpg",
            "2025_10_29__13_47_55__89.jpg",
            "2025_10_29__13_49_28__92.jpg",
            "2025_10_29__13_56_37__2.jpg",
            "2025_10_29__14_03_42__67.jpg",
            "2025_10_29__14_07_58__19.jpg",
            "2025_10_29__14_08_51__62.jpg",
            "2025_10_29__14_17_35__29.jpg",
            "2025_10_29__14_25_18__43.jpg",
            "2025_10_29__14_26_33__01.jpg",
            "2025_10_29__14_26_35__85.jpg",
            "2025_10_31__13_08_15__36.jpg",
            "2025_10_31__13_46_22__03.jpg",
            "2025_10_31__13_48_40__27.jpg",
            "2025_10_31__13_52_38__16.jpg",
            "2025_10_31__13_52_43__51.jpg",
            "2025_10_31__13_53_40__57.jpg",
            "2025_10_31__13_56_00__42.jpg",
            "2025_10_31__13_56_48__6.jpg",
            "2025_10_31__14_07_50__85.jpg",
            "2025_10_31__14_10_47__9.jpg",
            "2025_10_31__14_23_13__54.jpg",
            "2025_10_31__14_27_25__35.jpg",
            "2025_10_31__14_35_53__13.jpg",
            "2025_10_31__14_36_32__17.jpg",
            "2025_10_31__14_36_58__47.jpg",
            "2025_10_31__14_39_23__94.jpg",
            "2025_11_02__13_12_00__68.jpg",
            "2025_11_02__13_15_18__72.jpg",
            "2025_11_02__13_15_49__5.jpg",
            "2025_11_02__13_16_01__35.jpg",
            "2025_11_02__13_16_01__86.jpg",
            "2025_11_02__13_19_05__75.jpg",
            "2025_11_02__13_19_08__45.jpg",
            "2025_11_02__13_19_13__97.jpg",
            "2025_11_02__13_19_45__05.jpg",
            "2025_11_02__13_24_03__63.jpg",
            "2025_11_02__13_24_25__54.jpg",
            "2025_11_02__13_25_05__9.jpg",
            "2025_11_02__13_26_14__88.jpg",
            "2025_11_02__13_31_15__06.jpg",
            "2025_11_02__13_34_36__6.jpg",
            "2025_11_02__13_34_46__77.jpg",
            "2025_11_02__13_36_00__58.jpg",
            "2025_11_02__13_46_45__79.jpg",
            "2025_11_02__13_54_04__11.jpg",
            "2025_11_02__13_54_54__27.jpg",
            "2025_11_02__13_59_56__24.jpg",
            "2025_11_02__14_00_55__63.jpg",
            "2025_11_02__14_03_45__12.jpg",
            "2025_11_02__14_04_17__47.jpg",
            "2025_11_02__14_05_22__72.jpg"
        ],
        "Natur": [
            "2024_05_20__19_51_15__09.jpg",
            "2024_05_30__21_31_13__10.jpg",
            "2024_05_30__21_37_10__46.jpg",
            "2024_05_30__21_39_00__33.jpg",
            "2024_10_14__13_28_15__68.jpg",
            "2025_10_29__14_34_56__33.jpg",
            "2025_10_31__12_13_20__11.jpg",
            "2025_10_31__12_14_12__27.jpg",
            "2025_11_01__13_09_36__52.jpg"
        ],
        "Nordbyen Hundepark": [
            "2025_11_03__12_55_47__32.jpg",
            "2025_11_03__12_56_51__5.jpg",
            "2025_11_03__12_57_06__24.jpg",
            "2025_11_03__13_03_51__47.jpg",
            "2025_11_03__13_05_15__36.jpg",
            "2025_11_03__13_31_40__15.jpg",
            "2025_11_03__13_40_20__62.jpg",
            "2025_11_03__13_42_06__16.jpg",
            "2025_11_03__13_42_41__23.jpg",
            "2025_11_03__13_42_59__87.jpg",
            "2025_11_03__13_43_33__49.jpg",
            "2025_11_03__13_51_01__93.jpg",
            "2025_11_06__14_47_37__21.jpg",
            "2025_11_06__14_50_19__97.jpg",
            "2025_11_06__14_55_48__1.jpg",
            "2025_11_06__14_55_50__64.jpg",
            "2025_11_06__14_56_17__69.jpg",
            "2025_11_06__14_56_24__71.jpg",
            "2025_11_06__14_58_24__73.jpg",
            "2025_11_06__14_58_28__15.jpg",
            "2025_11_06__14_58_42__28.jpg",
            "2025_11_06__14_59_20__92.jpg",
            "2025_11_06__15_08_02__39.jpg",
            "2025_11_06__15_08_55__77.jpg",
            "2025_11_06__15_09_02__41.jpg"
        ],
        "Vann": [
            "2024_05_30__21_31_13__10.jpg",
            "2024_05_30__21_37_10__46.jpg",
            "2024_05_30__21_39_00__33.jpg"
        ]
    },
    "directory": "img"
}
Object.freeze(IMAGE_DATA);
